
export const PERMISSION_LOCATION = 'PERMISSION_LOCATION';
export const ASK_PERMISSION_LOCATION = 'ASK_PERMISSION_LOCATION';
export const PERMISSION_CAMERA = 'PERMISSION_CAMERA';
export const ASK_PERMISSION_CAMERA = 'ASK_PERMISSION_CAMERA';
export const PERMISSION_PHOTO_LIBRARY = 'PERMISSION_PHOTO_LIBRARY';
export const ASK_PERMISSION_PHOTO_LIBRARY = 'ASK_PERMISSION_PHOTO_LIBRARY';
